micronaut:
  server:
    port: 8080
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    url: 'jdbc:postgresql://localhost:5432/pix'
    username: 'admin'
    password: 'admin'
config:
  authentication:
    apiKey: '123'
  bankingPartner:
    environment: sandbox
    projectId: 5797150046814208
    privateKeyPath: 'local/bankingPartnerPrivateKey.pem'
  events:
    transactionFinalizedTopic:
      projectId: 'ume-local'
      topicId: 'topic-local'
    notifications:
      projectId: 'ume-local'
      topicId: 'topic-local'
      transactionFinalizedEventName: 'payanywhere-transaction-finalized'
    refund:
      projectId: 'ume-local'
      topicId: 'topic-refund-local'
  featureFlags:
    emitTransactionFinalizedEvent: false
  refund:
    paymentLeftoverCutoffValue: 1.5