version: '3.1'
services:
  pay_anywhere_db:
    image: postgres
    container_name: pg-pay-anywhere
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: pay-anywhere
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin